import sys
import os
import json
from datetime import datetime
from PIL import Image as PILImage

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether, PageBreak, HRFlowable)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to calculate total page count dynamically
    and draw formal header/footer on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count):
        self.saveState()
        
        # Colors
        border_color = colors.HexColor("#CCCCCC")
        text_color = colors.HexColor("#555555")
        
        # Dimensions
        page_width, page_height = A4
        margin = 36  # 0.5 inch
        
        # Running Header (Pages > 1)
        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(colors.HexColor("#333333"))
            self.drawString(margin, page_height - 25, "LabelGuard Inspection Report")
            
            self.setFont("Helvetica", 8)
            self.setFillColor(text_color)
            self.drawRightString(page_width - margin, page_height - 25, f"Inspection ID: {getattr(self, 'inspection_id', '')}")
            
            self.setStrokeColor(border_color)
            self.setLineWidth(0.5)
            self.line(margin, page_height - 30, page_width - margin, page_height - 30)

        # Running Footer (All pages)
        self.setStrokeColor(border_color)
        self.setLineWidth(0.5)
        self.line(margin, 40, page_width - margin, 40)
        
        self.setFont("Helvetica", 8)
        self.setFillColor(text_color)
        
        footer_text = f"LabelGuard Inspection System  |  Inspection ID: {getattr(self, 'inspection_id', '')}  |  Generated On: {getattr(self, 'gen_timestamp', '')}"
        self.drawString(margin, 26, footer_text)
        
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(page_width - margin, 26, page_str)
        
        # Final page prototype disclaimer
        if self._pageNumber == page_count:
            self.setFont("Helvetica-Oblique", 7)
            self.setFillColor(colors.HexColor("#777777"))
            disclaimer = "This report is generated by the LabelGuard inspection system for inspection assistance and record keeping. It is not a government-issued certificate."
            self.drawCentredString(page_width / 2.0, 14, disclaimer)
            
        self.restoreState()


def generate_pdf_report(payload_path, output_path):
    with open(payload_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Extract Payload Data (supports both flat and nested product/user payloads)
    prod = data.get("product") if isinstance(data.get("product"), dict) else data
    user_info = data.get("user") if isinstance(data.get("user"), dict) else data.get("officer", {})

    inspection_id = data.get("inspectionId") or prod.get("inspectionId", "INSP-UNKNOWN")
    created_at_raw = data.get("createdAt") or prod.get("createdAt", "")
    try:
        dt = datetime.fromisoformat(created_at_raw.replace("Z", "+00:00"))
        created_at_str = dt.strftime("%B %d, %Y - %H:%M:%S UTC")
    except Exception:
        created_at_str = created_at_raw or datetime.now().strftime("%B %d, %Y - %H:%M:%S")

    gen_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    officer = data.get("officer") or user_info or {}
    officer_name = officer.get("fullName") or officer.get("username") or "Inspection Officer"
    officer_dept = officer.get("department") or "Legal Metrology Inspection Division"
    officer_desig = officer.get("designation") or "Senior Compliance Auditor"
    officer_id = officer.get("id") or str(officer.get("_id", "")) or "OFFICER-REG-01"

    structured = data.get("structuredData") or prod.get("structuredData", {})
    compliance = data.get("complianceResults") or prod.get("complianceResults", {})
    original_images = data.get("originalImages") or prod.get("originalImages", [])
    backend_root = data.get("backendRoot") or prod.get("backendRoot", os.getcwd())

    # Build PDF Document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=50
    )

    styles = getSampleStyleSheet()
    
    # Custom Palette & Styles
    c_primary = colors.HexColor("#111111")
    c_secondary = colors.HexColor("#333333")
    c_muted = colors.HexColor("#666666")
    c_border = colors.HexColor("#D0D0D0")
    
    style_title = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=c_primary,
        spaceAfter=2
    )
    
    style_subtitle = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=c_muted,
        spaceAfter=12
    )
    
    style_h2 = ParagraphStyle(
        'SectionHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=c_primary,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )
    
    style_body = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=c_secondary
    )

    style_body_bold = ParagraphStyle(
        'BodyDarkBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=13,
        textColor=c_primary
    )
    
    style_caption = ParagraphStyle(
        'ImageCaption',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8,
        leading=11,
        textColor=c_muted,
        alignment=1, # Center
        spaceBefore=4,
        spaceAfter=12
    )

    story = []


    #header section 
    story.append(Paragraph("INSPECTION REPORT", style_title))
    story.append(Paragraph("Packaged Commodity Label Compliance Assessment", style_subtitle))
    story.append(HRFlowable(width="100%", thickness=1, color=c_primary, spaceBefore=0, spaceAfter=12))

    meta_data = [
        [Paragraph("<b>Inspection ID:</b>", style_body), Paragraph(inspection_id, style_body_bold),
         Paragraph("<b>Inspection Officer:</b>", style_body), Paragraph(officer_name, style_body)],
        [Paragraph("<b>Date of Inspection:</b>", style_body), Paragraph(created_at_str, style_body),
         Paragraph("<b>Department / Org:</b>", style_body), Paragraph(officer_dept, style_body)],
        [Paragraph("<b>Inspection Type:</b>", style_body), Paragraph("Package Label Compliance Inspection", style_body),
         Paragraph("<b>Officer ID:</b>", style_body), Paragraph(officer_id, style_body)]
    ]

    meta_table = Table(meta_data, colWidths=[110, 160, 110, 143])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 14))




    #commudity details section
    story.append(Paragraph("COMMODITY DETAILS", style_h2))
    
    commodity_rows = []
    
    # Format Commodity Declarations cleanly
    p_name = structured.get("productName", {})
    p_name_val = p_name.get("value") if isinstance(p_name, dict) else p_name
    if p_name_val:
        commodity_rows.append(["Product Name / Common Name", str(p_name_val)])

    net_q = structured.get("netQuantity", {})
    if isinstance(net_q, dict) and net_q.get("value"):
        commodity_rows.append(["Net Quantity", f"{net_q.get('value')} {net_q.get('unit', '')}".strip()])
    elif net_q and not isinstance(net_q, dict):
        commodity_rows.append(["Net Quantity", str(net_q)])

    mrp_d = structured.get("mrp", {})
    if isinstance(mrp_d, dict) and mrp_d.get("value") is not None:
        commodity_rows.append(["Maximum Retail Price (MRP)", f"Rs. {mrp_d.get('value')} (Incl. of all taxes)"])
    elif mrp_d and not isinstance(mrp_d, dict):
        commodity_rows.append(["Maximum Retail Price (MRP)", f"Rs. {mrp_d}"])

    mfg = structured.get("manufacturer")
    if isinstance(mfg, list) and len(mfg) > 0:
        mfg_str = ", ".join([item.get("value") if isinstance(item, dict) else str(item) for item in mfg])
        commodity_rows.append(["Manufacturer / Packer Name & Address", mfg_str])
    elif mfg:
        commodity_rows.append(["Manufacturer / Packer Name & Address", str(mfg)])

    origin = structured.get("countryOfOrigin", {})
    origin_val = origin.get("value") if isinstance(origin, dict) else origin
    if origin_val:
        commodity_rows.append(["Country of Origin", str(origin_val)])

    mfg_date = structured.get("manufacturingDate", {})
    mfg_date_val = mfg_date.get("value") if isinstance(mfg_date, dict) else mfg_date
    if mfg_date_val:
        commodity_rows.append(["Manufacturing / Packing Date", str(mfg_date_val)])

    best_b = structured.get("bestBefore", {})
    best_b_val = best_b.get("value") if isinstance(best_b, dict) else best_b
    if best_b_val:
        commodity_rows.append(["Best Before / Shelf Life", str(best_b_val)])

    care = structured.get("consumerCare", {})
    if isinstance(care, dict):
        phone = care.get("phone", {}).get("value") if isinstance(care.get("phone"), dict) else care.get("phone")
        email = care.get("email", {}).get("value") if isinstance(care.get("email"), dict) else care.get("email")
        care_items = []
        if phone: care_items.append(f"Phone: {phone}")
        if email: care_items.append(f"Email: {email}")
        if care_items:
            commodity_rows.append(["Consumer Care Details", ", ".join(care_items)])

    if not commodity_rows:
        commodity_rows.append(["Detected Declarations", "No structured commodity declarations detected."])

    table_data = []
    for row in commodity_rows:
        table_data.append([
            Paragraph(f"<b>{row[0]}</b>", style_body),
            Paragraph(row[1], style_body)
        ])

    comm_table = Table(table_data, colWidths=[190, 333])
    comm_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#FAFAFA")),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(comm_table)
    story.append(Spacer(1, 14))


    # overall assessment section
    story.append(Paragraph("OVERALL ASSESSMENT", style_h2))
    
    overall_status = compliance.get("overallStatus", "REQUIRES REVIEW").upper()
    pass_count = compliance.get("passCount", 0)
    warn_count = compliance.get("warnCount", 0)
    fail_count = compliance.get("failCount", 0)
    total_rules = pass_count + warn_count + fail_count

    assessment_text = f"<b>STATUS: {overall_status}</b>"
    summary_text = f"Rules Evaluated: {total_rules}  |  Compliant: {pass_count}  |  Warnings: {warn_count}  |  Non-Compliant: {fail_count}"

    assessment_box_data = [
        [Paragraph(f"<font size=13 color='#111111'><b>{overall_status}</b></font>", ParagraphStyle('CenterBold', parent=styles['Normal'], alignment=1))],
        [Paragraph(f"<font size=9 color='#444444'>{summary_text}</font>", ParagraphStyle('CenterSub', parent=styles['Normal'], alignment=1))]
    ]

    assess_table = Table(assessment_box_data, colWidths=[523])
    assess_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8F9FA")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#111111")),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(assess_table)
    story.append(Spacer(1, 14))


    # rule verification breakdown section

    story.append(Paragraph("RULE VERIFICATION BREAKDOWN", style_h2))

    rule_results = compliance.get("results", [])
    rule_table_data = [
        [
            Paragraph("<b>Rule Reference</b>", style_body_bold),
            Paragraph("<b>Requirement Description</b>", style_body_bold),
            Paragraph("<b>Observed / Extracted Value</b>", style_body_bold),
            Paragraph("<b>Status</b>", style_body_bold)
        ]
    ]

    for rule in rule_results:
        rule_ref = rule.get("ruleRef", "LMPC 2011")
        rule_name = rule.get("ruleName", "Requirement Check")
        extracted_val = rule.get("extractedValue", "Not detected")
        status = rule.get("status", "FAIL")

        rule_table_data.append([
            Paragraph(rule_ref, style_body),
            Paragraph(rule_name, style_body),
            Paragraph(extracted_val, style_body),
            Paragraph(f"<b>{status}</b>", style_body_bold)
        ])

    rule_table = Table(rule_table_data, colWidths=[120, 160, 173, 70], repeatRows=1)
    rule_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#EEEEEE")),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(rule_table)
    story.append(Spacer(1, 16))


   #ALL EVIDENCE IMAGES SECTION
    story.append(KeepTogether([
        Paragraph("EVIDENCE IMAGES", style_h2),
        Paragraph(f"All scanned packaging surfaces associated with Inspection ID: <b>{inspection_id}</b>", style_subtitle)
    ]))

    if not original_images:
        story.append(Paragraph("No physical packaging images recorded for this inspection.", style_body))
    else:
        for idx, img_rel_path in enumerate(original_images, start=1):
            # Resolve image disk path safely
            if os.path.isabs(img_rel_path):
                full_img_path = img_rel_path
            else:
                full_img_path = os.path.normpath(os.path.join(backend_root, img_rel_path))

            if not os.path.exists(full_img_path):
                # Try relative to cwd
                full_img_path = os.path.normpath(os.path.join(os.getcwd(), img_rel_path))

            if os.path.exists(full_img_path):
                try:
                    with PILImage.open(full_img_path) as pil_img:
                        orig_w, orig_h = pil_img.size

                    #calculate aspect ratio scaling to fit A4 page width n
                    max_w = 470.0
                    max_h = 320.0

                    aspect = orig_h / float(orig_w) if orig_w > 0 else 1.0

                    scaled_w = max_w
                    scaled_h = max_w * aspect

                    if scaled_h > max_h:
                        scaled_h = max_h
                        scaled_w = max_h / aspect

                    img_flowable = Image(full_img_path, width=scaled_w, height=scaled_h)

                    filename = os.path.basename(full_img_path)
                    caption_text = f"Evidence Image {idx:02d} - Packaging Surface ({orig_w}x{orig_h}px) | File: {filename}"

                    image_block = KeepTogether([
                        img_flowable,
                        Paragraph(caption_text, style_caption),
                        Spacer(1, 10)
                    ])

                    story.append(image_block)

                except Exception as img_err:
                    story.append(Paragraph(f"Evidence Image {idx:02d}: Unable to render image ({str(img_err)})", style_body))
            else:
                story.append(Paragraph(f"Evidence Image {idx:02d}: Image file missing at path ({img_rel_path})", style_body))

    story.append(Spacer(1, 10))

    
    non_compliant_rules = [r for r in rule_results if r.get("status") in ["FAIL", "WARNING"]]
    
    if non_compliant_rules:
        story.append(KeepTogether([
            Paragraph("EVIDENCE TO VIOLATION MAPPING", style_h2),
            Paragraph("Detailed breakdown connecting non-compliant declarations with inspected packaging surfaces:", style_subtitle)
        ]))

        violation_table_data = [
            [
                Paragraph("<b>Violation / Warning</b>", style_body_bold),
                Paragraph("<b>Rule Reference</b>", style_body_bold),
                Paragraph("<b>Evidence Reference & OCR Context</b>", style_body_bold)
            ]
        ]

        for v in non_compliant_rules:
            v_name = v.get("ruleName", "Violation")
            v_ref = v.get("ruleRef", "LMPC 2011")
            v_exp = v.get("explanation", "Declaration missing or non-compliant.")
            bbox = v.get("evidence")

            bbox_info = f"Bounding Box: {bbox}" if bbox else "Full surface scan inspected (Declaration missing)"
            evidence_desc = f"Associated Surfaces: Evidence Image 01 - {len(original_images)}<br/>{bbox_info}"

            violation_table_data.append([
                Paragraph(f"<b>{v_name}</b><br/>{v_exp}", style_body),
                Paragraph(v_ref, style_body),
                Paragraph(evidence_desc, style_body)
            ])

        v_table = Table(violation_table_data, colWidths=[180, 140, 203])
        v_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#EEEEEE")),
            ('GRID', (0, 0), (-1, -1), 0.5, c_border),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(v_table)
        story.append(Spacer(1, 16))




    #inceotion officer sign 
    officer_block = [
        Paragraph("INSPECTION OFFICER SIGN-OFF", style_h2),
        Spacer(1, 4),
        Table([
            [Paragraph("<b>Name:</b>", style_body), Paragraph(officer_name, style_body),
             Paragraph("<b>Designation:</b>", style_body), Paragraph(officer_desig, style_body)],
            [Paragraph("<b>Department:</b>", style_body), Paragraph(officer_dept, style_body),
             Paragraph("<b>Officer ID:</b>", style_body), Paragraph(officer_id, style_body)],
            [Paragraph("<b>Signature:</b>", style_body), Paragraph("___________________________", style_body),
             Paragraph("<b>Date:</b>", style_body), Paragraph("___________________________", style_body)]
        ], colWidths=[90, 170, 90, 173], style=[
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ])
    ]

    story.append(KeepTogether(officer_block))

    # Custom Canvas Class Instance Hook
    def make_canvas(*args, **kwargs):
        c = NumberedCanvas(*args, **kwargs)
        c.inspection_id = inspection_id
        c.gen_timestamp = gen_timestamp
        return c

    doc.build(story, canvasmaker=make_canvas)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_report_pdf.py <payload_json_path> <output_pdf_path>")
        sys.exit(1)

    payload_path = sys.argv[1]
    output_pdf_path = sys.argv[2]

    try:
        generate_pdf_report(payload_path, output_pdf_path)
        print(f"SUCCESS: PDF generated at {output_pdf_path}")
    except Exception as e:
        print(f"ERROR: {str(e)}")
        sys.exit(1)
